name: Continuous Integration

on: [push]

jobs:
  setup:
    name: Setup Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Restore cached node modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

  typecheck:
    name: Run typecheck
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - name: Type check
        run: npm run typecheck

  lint:
    name: Run linter
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - name: Lint
        run: npm run lint
